# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.22.2
openblas64__info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SU

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
def null_array(n):
    x=np.zeros(10)
    return x
print(null_array(10))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [7]:
x = np.array([100, 200, 300])
print("size of the array:", x.size)
print("Memory size of one array element in bytes:", x.itemsize)
print("Memory size of numpy array in bytes:", x.size * x.itemsize)

size of the array: 3
Memory size of one array element in bytes: 4
Memory size of numpy array in bytes: 12


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [3]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:
z = np.arange(10,50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
z = np.random.uniform((3,3,3))
print(z)

[1.65705453 2.20968389 1.67282881]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [25]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.006450454662066729 0.968283515804567


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [26]:
z = np.random.random(30)
m = z.mean()
print(m)

0.4710080946385679


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [44]:
z = np.ones((5,5))
z[1:-1, 1:-1]=0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [43]:
x = np.ones((4,4))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [65]:
z = np.diag(1+np.arange(4), k = -3)
print(z)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [63]:
z = np.zeros((8,8), dtype=int)
z[1::2, ::2]= 1
z[::2, 1::2]= 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [33]:
print(np.unravel_index(100, (6,7,8)))


(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [37]:
array = np.array([[0,1],[1,0]])
z = np.tile(array,(4,4))
print(z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [40]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.13580322 0.32334873 0.57497243 0.53643004 0.16389614]
 [0.61992528 0.         0.53709348 0.87821376 0.48508994]
 [0.19885517 0.41419354 0.96407597 0.02826653 1.        ]
 [0.12145095 0.50879666 0.39821759 0.64698516 0.47254269]
 [0.89339932 0.4867001  0.69492176 0.64815923 0.00435655]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [45]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

C:\Users\Mate Kovacs\AppData\Local\Temp\ipykernel_9288\134386954.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [46]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [56]:
print(sum(range(5), -1)) #0+1+2+3+4+(-1)
from numpy import *
print(sum(range(5), -1)) #0+1+2+3+4 on axis=-1


10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [58]:
Z = np.arange(3)
Z ** Z # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2 # = [0, 1, 2]
Z < - Z # = [False, False, False]
1j * Z # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1 # = [0, 1, 2] #array([0., 1., 2.])
Z < Z > Z # valueError

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [59]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


C:\Users\Mate Kovacs\AppData\Local\Temp\ipykernel_9288\1729466501.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\Mate Kovacs\AppData\Local\Temp\ipykernel_9288\1729466501.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [60]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([  7.,   5., -10., -10.,  -3.,   9.,  -9.,   4.,   7.,  -3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [61]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])