# Numpy exercises

***“After climbing a great hill, one only finds that there are many more hills to climb.”***

If you are reading this notebook means that you have completed 30 exercises on Numpy but you are hungry for knowledge and want to practice more. 

If that's the case, take these exercises as a practice guide to master your Numpy skills and maybe to remember some mathematical concepts, that might be helpful for future projects.


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [9]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-02-24 2022-02-25 2022-02-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [10]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [11]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [13]:
z = np.random.uniform(0, 10, 10)
print (z - z%1)

print (np.floor(z))
print (np.ceil(z)-1)
print (z.astype(int))
print (np.trunc(z))


[3. 4. 3. 0. 9. 2. 9. 2. 1. 5.]
[3. 4. 3. 0. 9. 2. 9. 2. 1. 5.]
[3. 4. 3. 0. 9. 2. 9. 2. 1. 5.]
[3 4 3 0 9 2 9 2 1 5]
[3. 4. 3. 0. 9. 2. 9. 2. 1. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [14]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)
             

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [15]:
def generate():
    for x in range(10):
      z = np.formiter(generate(), dtype=float,count=-1)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [16]:
z = np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [17]:
z = np.random.random(10)
z.sort()
print(z)
                 

[0.11343292 0.12000258 0.13083541 0.2119486  0.24088058 0.33786685
 0.41797989 0.4180165  0.46739749 0.47821308]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [18]:
z = np.arange(10)
np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [20]:
A = np.random.randint(0,2,6)
B = np.random.randint(0,2,6)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equel)
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [22]:
z = np.zeros(10)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [24]:
z = np.random.random((10,2))
x,y = z[:,0], z[:,1]
R = np.sqrt(x**2+y**2)
T = np.arctan2(y,x)
print(R)
print(T)

[0.71579735 1.07112914 1.18173069 1.12412799 0.53527638 0.8554394
 0.49255705 0.8293443  0.29104158 0.71096748]
[1.51175396 1.02178071 0.7239745  0.93778292 0.43779268 1.25258063
 1.0165726  0.76550801 0.38799372 0.10448145]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [27]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.         0.20333922 0.04084487 0.33667723 0.03734158 0.23109391
 0.37153962 0.24287174 0.16924683 0.56921278]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [28]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [29]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [32]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [34]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [35]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

37


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [36]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\Mate Kovacs\AppData\Local\Temp\ipykernel_14800\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [39]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
#import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
#import scipy.spatial

#Z = np.random.random((10,2))
#D = scipy.spatial.distance.cdist(Z,Z)
#print(D)

[[0.         0.9657811  0.58680987 0.05718366 0.74393766 0.14173156
  0.79718125 0.65210037 0.22821936 0.70397158]
 [0.9657811  0.         0.38663302 0.90952605 0.47930861 0.83043397
  0.84133134 0.42166129 0.78629139 0.3191914 ]
 [0.58680987 0.38663302 0.         0.52979626 0.30867084 0.44798543
  0.73390036 0.28877537 0.43586072 0.2379692 ]
 [0.05718366 0.90952605 0.52979626 0.         0.69012012 0.08506057
  0.77573994 0.60351842 0.19106762 0.65160974]
 [0.74393766 0.47930861 0.30867084 0.69012012 0.         0.60671894
  1.04248482 0.59018901 0.67094109 0.51720072]
 [0.14173156 0.83043397 0.44798543 0.08506057 0.60671894 0.
  0.76534096 0.54459215 0.17417915 0.58360829]
 [0.79718125 0.84133134 0.73390036 0.77573994 1.04248482 0.76534096
  0.         0.46380835 0.59236909 0.56075204]
 [0.65210037 0.42166129 0.28877537 0.60351842 0.59018901 0.54459215
  0.46380835 0.         0.43318039 0.10513391]
 [0.22821936 0.78629139 0.43586072 0.19106762 0.67094109 0.17417915
  0.59236909 0.43318

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [40]:
z = np.arange(10, dtype=np.int32)
z = z.astype(np.float32, copy=False)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [41]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\Mate Kovacs\AppData\Local\Temp\ipykernel_14800\1271915251.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [42]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [43]:
n = 6
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [44]:
x = np.random.rand(5,10)
y = x - x.mean(axis=1, keepdims=True)
print(y)

[[ 0.13880638  0.08675945 -0.03996823 -0.03564843 -0.26526775 -0.18458697
   0.26991747 -0.37071603  0.3426697   0.05803441]
 [ 0.26499283 -0.32358647  0.35278191  0.1263248  -0.5119471  -0.5492687
   0.33375297 -0.1635274   0.18417368  0.28630348]
 [-0.00867193  0.18249555 -0.11123256  0.05466674  0.11097066  0.30858632
  -0.26882722  0.19759903 -0.23116766 -0.23441893]
 [ 0.44732613  0.15690175  0.26910598 -0.2443004  -0.35291006 -0.0782377
   0.0138582   0.16729878 -0.29979612 -0.07924655]
 [ 0.34631914 -0.2478484   0.27310898 -0.28022053  0.1881352  -0.33917785
   0.34636464  0.29222323 -0.43359789 -0.14530652]]


In [46]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.01581075  0.16668516 -0.60113279  0.16233172  0.20192682 -0.07065142
  -0.13739312  0.21649666 -0.03882291  0.08474913]
 [-0.5049086   0.26292264 -0.24752867  0.14305422  0.12846398 -0.23284158
   0.06862208 -0.17921382  0.25450581  0.30692393]
 [-0.42680839  0.09824148  0.03440659  0.04281348 -0.08056381 -0.20363632
  -0.45920003  0.29559738  0.42411437  0.27503524]
 [ 0.19680312 -0.5128845  -0.3498937   0.37407204 -0.19540039  0.3557947
   0.08482934  0.30806107  0.24234617 -0.50372784]
 [-0.21981319 -0.30247183 -0.16003599 -0.08983363 -0.33437865  0.03925058
   0.24926851  0.39783262  0.05749511  0.36268648]]


#### 59. How to sort an array by the nth column? (★★☆)

In [47]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 8 2]
 [6 7 0]
 [4 9 0]]
[[6 7 0]
 [1 8 2]
 [4 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [48]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [49]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5131546605378818


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [50]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [52]:
class NameArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj,'name', "no name")
z = NameArray(np.arange(10), "range_10")
print(z.name)
    

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [58]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[5. 4. 1. 3. 2. 1. 5. 4. 2. 3.]
[9. 7. 1. 5. 3. 1. 9. 7. 3. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [59]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [60]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [61]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)


[[45 29 51 38]
 [62 58 65 59]
 [53 68 48 60]]


In [62]:
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[45 29 51 38]
 [62 58 65 59]
 [53 68 48 60]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [66]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)



[0.50001732 0.50254621 0.37758268 0.50792016 0.41993392 0.53912947
 0.30761026 0.71498052 0.42698067 0.5081189 ]


In [68]:
# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.500017
1    0.502546
2    0.377583
3    0.507920
4    0.419934
5    0.539129
6    0.307610
7    0.714981
8    0.426981
9    0.508119
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))




array([1.20693246, 2.1956561 , 0.97773729, 0.36755442, 0.85922725])

In [70]:

# Fast version
np.sum(A * B.T, axis=1)

array([1.20693246, 2.1956561 , 0.97773729, 0.36755442, 0.85922725])

In [71]:
# Faster version
np.einsum("ij,ji->i", A, B)

array([1.20693246, 2.1956561 , 0.97773729, 0.36755442, 0.85922725])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [72]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [74]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [75]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1,  3) ( 1, 43) ( 1, 72) ( 1, 80) ( 3, 43) ( 8, 38) ( 8, 89) ( 9, 47)
 ( 9, 87) (19, 34) (19, 59) (20, 32) (20, 86) (29, 79) (29, 93) (32, 86)
 (34, 59) (38, 89) (41, 82) (41, 92) (47, 87) (51, 58) (51, 84) (58, 84)
 (72, 80) (72, 87) (72, 94) (79, 93) (82, 92) (87, 94)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [76]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [77]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [78]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [79]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.60542044,  0.19604536,  0.96933297,  0.82694997, -0.21613301,
       -0.45590214,  0.427449  ,  0.59979041,  0.60533959, -0.97811919,
        0.22551778,  0.45179424,  0.58094067, -0.74491385, -0.36905411,
        0.27161718, -0.16454064,  0.32727158, -0.27178791, -0.92622896,
        0.47863228,  0.22290728, -0.04855808,  0.16313446, -0.55922277,
       -0.73382784,  0.3833124 , -0.51634542,  0.99687226, -0.19272227,
       -0.39280032, -0.94018313,  0.39554496,  0.60465793, -0.93286106,
       -0.94737827,  0.95861385, -0.11689091, -0.6223305 ,  0.43577947,
       -0.82014455,  0.03691654,  0.77809224,  0.11622001, -0.55478534,
       -0.43429172, -0.93700819, -0.50816736, -0.03029285,  0.93274436,
       -0.55996085, -0.39515159,  0.94637844, -0.85515212,  0.21967455,
        0.11230088, -0.28469427,  0.59009791, -0.06306346, -0.44432187,
       -0.67415993,  0.28069648, -0.52804227, -0.63182819, -0.23877465,
        0.63536108, -0.00326856, -0.98014749,  0.24713276,  0.30

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [80]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.09220468 3.06677545 9.37119707 3.54428019 0.77063148 0.99069394
 0.62970231 3.68661529 0.96014362 8.18419057]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [81]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.99605772  9.45605508  1.14573266  3.28524675 12.86620927  5.38755371
   5.57371151  3.60543203  6.26750082 13.05625602]
 [ 4.60527513  4.85238134  1.04126494  4.88175106 12.5246857   9.57367032
   6.85439328 11.12181581  4.20700583  2.46657909]
 [ 0.9038191   6.09648995  0.65310264  1.07768558 13.26009979  2.22350177
   2.53722005  0.51311072  4.30114747  9.54734047]
 [ 8.5161933   2.56875827 15.0695889   8.01087574  1.45076854 12.22617617
   3.12669884 14.39702084 13.49238409  1.53083088]
 [ 6.63973334  4.81090179  2.08924584  6.79756804 15.69646899  7.19751026
   7.61040184  8.63401072  0.87916334  1.51340059]
 [12.18806217  9.572672   15.04620593 11.96241986  1.2081233   4.84720102
   9.19134688  7.12990245  8.28667496  9.15080359]
 [ 3.80089592  1.32190831 11.00926891  3.29244236  2.53976649 13.29014172
   1.27267747 15.25271312 12.09400482  1.52048062]
 [14.19709279 15.82807046 13.09122725 14.29351545  0.96738271  3.18428126
  14.11857024  0.87106628  1.60025217 16.51745945]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [82]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 2 9 5 6 1 4 3 1 5]
 [2 4 6 3 1 0 4 1 1 3]
 [6 6 9 3 7 9 6 9 6 8]
 [4 9 4 7 0 0 4 6 3 7]
 [5 1 1 2 1 2 9 4 0 8]
 [6 4 0 3 8 6 7 7 4 4]
 [4 7 3 8 8 1 7 6 6 3]
 [1 5 3 6 7 4 4 9 8 7]
 [7 6 1 7 1 0 0 1 6 2]
 [7 1 6 1 8 5 5 6 9 2]]
[[0 0 0 0 0]
 [0 6 2 9 5]
 [0 2 4 6 3]
 [0 6 6 9 3]
 [0 4 9 4 7]]


C:\Users\Mate Kovacs\AppData\Local\Temp\ipykernel_14800\1159162857.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [84]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [85]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [86]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [87]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 4]
   [1 2 1]
   [0 0 4]]

  [[4 4 3]
   [2 1 2]
   [0 4 2]]

  [[4 3 3]
   [1 2 3]
   [4 2 3]]

  [[3 3 4]
   [2 3 3]
   [2 3 1]]

  [[3 4 2]
   [3 3 3]
   [3 1 4]]

  [[4 2 3]
   [3 3 3]
   [1 4 1]]

  [[2 3 3]
   [3 3 0]
   [4 1 3]]

  [[3 3 4]
   [3 0 0]
   [1 3 2]]]


 [[[1 2 1]
   [0 0 4]
   [3 4 0]]

  [[2 1 2]
   [0 4 2]
   [4 0 1]]

  [[1 2 3]
   [4 2 3]
   [0 1 0]]

  [[2 3 3]
   [2 3 1]
   [1 0 1]]

  [[3 3 3]
   [3 1 4]
   [0 1 1]]

  [[3 3 3]
   [1 4 1]
   [1 1 3]]

  [[3 3 0]
   [4 1 3]
   [1 3 0]]

  [[3 0 0]
   [1 3 2]
   [3 0 3]]]


 [[[0 0 4]
   [3 4 0]
   [2 0 0]]

  [[0 4 2]
   [4 0 1]
   [0 0 0]]

  [[4 2 3]
   [0 1 0]
   [0 0 4]]

  [[2 3 1]
   [1 0 1]
   [0 4 2]]

  [[3 1 4]
   [0 1 1]
   [4 2 4]]

  [[1 4 1]
   [1 1 3]
   [2 4 4]]

  [[4 1 3]
   [1 3 0]
   [4 4 1]]

  [[1 3 2]
   [3 0 3]
   [4 1 3]]]


 [[[3 4 0]
   [2 0 0]
   [3 2 1]]

  [[4 0 1]
   [0 0 0]
   [2 1 2]]

  [[0 1 0]
   [0 0 4]
   [1 2 4]]

  [[1 0 1]
   [0 4 2]
   [2 4 1]]

  [[0 1 1]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [88]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2 10 11 14  8]
 [10  5 10 13 13]
 [11 10  4 42  6]
 [14 13 42  4  5]
 [ 8 13  6  5  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [89]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [90]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [91]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [92]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


In [93]:
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9997 9995 9996 9998]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [94]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [96]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [100]:
x = np.random.rand(5e7)

%timeit np.power(x,3)

%timeit x*x*x

%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [101]:
A = np.random.randint(0,5,(8,3))

B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)

rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]

print(rows)

[2 3 4 5 6 7]


In [102]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [103]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 2 1]
 [2 3 3]
 [1 1 3]
 [3 4 2]
 [4 1 1]
 [4 1 1]
 [3 2 4]
 [0 2 2]
 [1 0 3]
 [1 0 2]]
[[1 2 1]
 [2 3 3]
 [1 1 3]
 [3 4 2]
 [4 1 1]
 [4 1 1]
 [3 2 4]
 [0 2 2]
 [1 0 3]
 [1 0 2]]
[[1 2 1]
 [2 3 3]
 [1 1 3]
 [3 4 2]
 [4 1 1]
 [4 1 1]
 [3 2 4]
 [0 2 2]
 [1 0 3]
 [1 0 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [104]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [105]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [107]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [106]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[0.19481418, 0.17728785, 0.3226857 , 0.07091816, 0.08829598,
        0.04324113, 0.2474612 , 0.90921541, 0.60748391, 0.23904409],
       [0.18231063, 0.16590918, 0.30197511, 0.0663665 , 0.08262897,
        0.04046583, 0.23157867, 0.85086022, 0.56849443, 0.22370178],
       [0.08663161, 0.07883785, 0.14349459, 0.03153648, 0.0392642 ,
        0.01922883, 0.11004313, 0.40431754, 0.27014105, 0.10630013],
       [0.01281552, 0.01166258, 0.02122733, 0.00466523, 0.0058084 ,
        0.00284454, 0.01627882, 0.05981119, 0.0399623 , 0.01572511],
       [0.19801053, 0.18019664, 0.32798005, 0.07208172, 0.08974466,
        0.04395059, 0.25152134, 0.92413304, 0.61745099, 0.24296612],
       [0.02711419, 0.02467488, 0.04491131, 0.00987037, 0.01228901,
        0.00601829, 0.03444158, 0.12654436, 0.08454945, 0.03327009],
       [0.15923422, 0.14490882, 0.26375187, 0.05796599, 0.07217001,
        0.03534377, 0.20226603, 0.74316049, 0.49653585, 0.19538618],
       [0.1596937 , 0.14532697, 0.2645129

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [110]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [109]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [111]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.2216967   0.25220595]
